variable "region" {
  type        = string
  default     = "us-east-1"
  description = "Current Region"
}

variable "access_key" {
  type        = string
  default     = "AKIA3YSEVGIWHZ4LPP7W"
  description = "Access Key"
}

variable "secret_key" {
  type        = string
  default     = "BrajK7h9yyxydfQMZBH1RqzbEsuiIrxBqASZsD/y"
  description = "Secret Access Key"
}

variable "host" {
  type        = string
  default     = "https://EF4C09F83D7E6CA95544DB9C69C1D4F0.gr7.us-east-1.eks.amazonaws.com"
  # description = "Secret Access Key"
}

variable "cluster_ca_certificate" {
  type        = string
  default     = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ESXdOREUyTkRFeE5Wb1hEVE16TURJd01URTJOREV4TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1JHClkrMmlSYzZjdEhhWjBjVkRORnpVNlhaR2t1Y3h1UGt1bElmUEFxQytXWGZ3S25SUTFRcmJtOHVpTnZabEdTUEwKWXpnSmhFbFI3UFhrb2NFT2VSYmRBVVB4eHhHTHl1eENGczZvbHpVVnNwSE1yUjhBU2lLbjlIeFdMYnNlWTBueAp1ZHc1WkR3NVgwTWl1RmxabFFvN0ZycGM0cFM0U21uNTRaZWE1VW4vL3ZyTDFMZzQ5L2hRK2NJeXczZTBPOTVHClhjd040WU9UZXZnR0xSUWlCQ3BYTGh3aUhTSHI0dmlmSFRxZHhzb3VhQnZTa3UxKzNObkhoRXhrQ1hXUUl1eXAKYUpnYnhYck14Q2pLWUEvVmsvdWg4cWlMQmdWTk1GS3pMNlhTMGlRTklHM0h3dHBIWUdTTXFRKyt3NndKMFJnLwpqQ2V0U1c0d1FvSDF2dDdMS0dFQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGNXNDbG84SmQ4S0JoVThHV3JzWTJSeG1DUmxNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ2VSMDhwQ3J1R0cxM0hGZDRvbwo3cnJZTjd1V0Jxci9nMWYyai84SzNsbUx5aTB6RlVVTE9XcVZQOGFZVmJMelNYOTJwcldyNk9rczlwbHVNSTVYCjAwSUY2NWRabE1qQmhpeTVQSVZnTUVIZnpGV1JJc0xmWEZWdHJrb1FaWWh1cGV4YW1SZlVQQU5QOVdOVmpHLzMKNHA0R3J0WFZkYXU5bXZxYjNueEFWaVMvcU9lVWxCbmNYQWlpTWRoOHFmcWRTTjhZZ2QrN0FEaXdPUEJKWHpQeAphbjlxYklLVlF3LzhpT3NzWVN6UGZYQzhGRG0xdkc5andRR0FEZmswUldyd0ZsY2hkL2I2SStMMHRhUzNKVmRCCjZMK0N0RThKSktBbzl4MlhkbHU2eVFEdTFwOG1WWTBLTytGNzVXa09kZ2RFaXdLd1FNUW5qYXNDTzFVVXd0ZFMKQjRvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  # description = "Secret Access Key"
}

variable "cluster_name" {
  type        = string
  default     = "dev"
  # description = "Secret Access Key"
}